### ISSUE TITLE
Finding element with highest confidence of '0'

### ISSUE THREAD

**Issue by sheelendragahlaut** [testdotai/appium-classifier-plugin#12]
One Element is found with highest confidence as '0'.

[ai] Setting confidence threshold to default value of 0.2
[ai] Retrieving data for all leaf-node elements on screen
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/elements' to command name 'findElements'
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/e7421f03-e644-49a5-a87c-435cdad57956/elements] with body: {"strategy":"xpath","selector":"//*[not(child::*)]","context":"","multiple":true}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"e7421f03-e644-49a5-a87c-435cdad57956","status":0,"value":[{"ELEMENT":"d1deb049-9c48-4d21-be64-99d410314289","rect":{"x":27,"y":65,"width":79,"height":46}},{"ELEMENT":"cc554552-c15c-461b-ba63-52878d4e0a84","rect":{"x":629,"y":47,"width":91,"height":82}},{"ELEMENT":"aa989bc5-af70-41bf-b133-6691b47fa670","rect":{"x":27,"y":172,"width":51,"height":51}},{"ELEMENT":"e2dce951-108d-4eec-b5fc-6a4e58c5db21","rect":{"x":105,"y":181,"width":102,"height":32}},{"ELEMENT":"ab4dcf06-a727-4e30-aa54-587bc8298b8c","rect":{"x":0,"y":245,"width":720,"height":2}},{"ELEMENT":"5bda0ee4-a207-4f74-a549-edf6039d9b12","rect":{"x":27,"y":273,"width":66,"height":30}},{"ELEMENT":"f7cc9b41-9d55-4868-aae6-52b5e997fb46","rect":{"x":27,"y":351,"width":51,"height":51}},{"ELEMENT":"03d04e2e-17ae-4525-b1ec-c940cf4b02a1","rect":{"x":105,"y":360,"width":203,"height":32}},{"ELEMENT":"41292536-e066-4fe9-a312-d45ec5ddcdf7","rect":{"x":27,"y":446,"width":51,"height":51}},{"ELEMENT":"5adfa1df-1735-4694-8f58-dca3b162f140","rect":{"x":105...
[ai] Getting window size in case we need to scale screenshot
[debug] [JSONWP Proxy] Matched '/window/current/size' to command name 'getWindowSize'
[debug] [JSONWP Proxy] Proxying [GET /window/current/size] to [GET http://localhost:8200/wd/hub/session/e7421f03-e644-49a5-a87c-435cdad57956/window/current/size] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"e7421f03-e644-49a5-a87c-435cdad57956\",\"status\":0,\"value\":{\"height\":1280,\"width\":720}}"
[ai] Getting screenshot to use for classifier
[debug] [JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/e7421f03-e644-49a5-a87c-435cdad57956/screenshot] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"e7421f03-e644-49a5-a87c-435cdad57956\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAIAAADhrPJqAAAAA3NCSVQICAjb4U\\/gAAAgAElEQVR4\\nnOzdd3hUVd4H8DO9z2QyyUx6B5JQAiF0BKkqKGJFdxVld1Vsa1tf27vqorvW1VVXUV8VRcVVWVBE\\nULp0SKEE0iCkTupMpmV6ue8fF8ZhUphM5iYBv5+HPyY3J+eeifvsfHPK77JGLnmBAAAAADCJPdgD\\nAAAAgEsfAgcAAAAwDoEDAAAAGIfAAQAAAIxD4AAAAADGIXAAAAAA4xA4AAAAgHHcwR4AAABc9LLT\\nNAkxiuy0uMCLFbUtTTpTRW3rYI2qn\\/5x36KsZHXQxaZ247trd5+qbxuUIV3UEDjCkRCrGJ2Z0Gbo\\nLD2t9Xh9vbQUC\\/lxKnmNVkcN2OAA4OKRnaZ5Yun8V1ZvifinskwinF0wPDE2KiFWQQhpajdp2407\\niqosVkekbpGdpinISV08My87TdN7y8Kyuu2FlUXldRF8mzFRUqmI3+237E5Pa4e5\\/7cYlqLOOT9C\\nEUKkIr5cLOx\\/579BLFQa7Ss+j\\/P2X24uyElxOD1bD5e\\/\\/fUuk8Xuo7pJFGIh\\/7Hfz5k8Ov2xN\\/9b\\nUXexZnwAYM6E3NRVz95usTqWvfB5pD6MJ+Sm3nfjjAm5qd1+t7Cs7r21uwvL6vpzi8Uz8267auIF\\nc0ZXFbWtn28+9P0vx\\/v0U1EykdFiD7wSp5L3fvd2Q+fJM819HR4h5B\\/3LRqWcnZWIy1eJRLwgho4\\n3Z6mdpPD5SaENLWbHvrnt2Hc5beJox41u\\/+9iIX8UZkJS+aNL8hJPVHd1Psf\\/YQQNoullEuGp2oK\\nslNONfRrYmrgby0U8J794wIBjysU8HLT466cOpLDYZ...
[ai] Turning screenshot into HTML image for use with canvas
[ai] Getting screenshot slices for each element
[ai] Making label predictions based on element images
[ai] Predictions for 11 element(s) took 0.492 seconds
[ai] Found 1 matching elements
[ai] Highest confidence of any element for desired label 'location' was 0
[ai] Resetting element response attribute setting to original value: ""
[UiAutomator2] Forwarding the following settings to the UiAutomator2 server: ["elementResponseAttributes"]

**Comment by jlipps** [comment]
@sheelendragahlaut are you using the latest version of the plugin?

**Comment by sheelendragahlaut** [comment]
@jlipps Yes, I am using latest version of plugin i.e. 2.1.0.

**Comment by jlipps** [comment]
ok thanks for the report, i was able to repro and fix. 2.1.1 should work correctly.
