### ISSUE TITLE
Cant find Python executable even if Python is installed on my machine

### ISSUE THREAD

**Issue by nishmastercoder** [testdotai/appium-classifier-plugin#16]
Hi,
I have Python version 3.7.3 installed on my windows 10 machine.
I tried to install this plugin into this machine.
While doing so I receive following error:-
 Building TensorFlow Node.js bindings
C:\Program Files\Appium\node_modules\@tensorflow\tfjs-node\scripts\install.js:161
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Program Files\Python\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134

Thanks & Regards,
Nishant Shah

**Comment by KazuCocoa** [comment]
`node-gyp` requires Python 2.
https://github.com/appium/appium/issues/12087#issuecomment-457909623

The `node-gyp` is optional so you can ignore it tho.
https://github.com/appium/appium-doctor/blob/b77e93f072a141c7a00ae8785b37a6bdd099be33/lib/general.js#L48-L73

**Comment by nishmastercoder** [comment]
Thanks @KazuCocoa . After downgrading to python2 this issue got resolved
