### ISSUE TITLE
tf.fromPixels() is renamed to tf.browser.fromPixels(),You can disable deprecation warnings with tf.disableDeprecationWarnings().

### ISSUE THREAD

**Issue by BSudheerR** [testdotai/appium-classifier-plugin#22]
Hi All , facing the following issue , while locating the element with ai. 

[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"5b49b524-d285-4e48-a12b-e74bd1e1bea3\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAAAtAAAAXwCAYAAAB7XHwkAAAABHNCSVQICAgIfAhkiAAAIABJREFU\\neJzs3XdYVGfePvCb3mFARES62FAZFQtqIrZYUmxE3USDUdM22RA1ebPvu\\/vGRLO7v3eLJWbT14ik\\nGjWiaWqighU7oIIFpKoUlaF35vfHOMcZ5kw5MDS5P9eVKzPnnJnzMDPCPc95nu9jYe0\\/WQkiIiIi\\nIjKJZUc3gIiIiIioK2GAJiIiIiKSgAGaiIiIiEgCBmgiIiIiIgkYoImIiIiIJGCAJiIiIiKSgAGa\\niIiIiEgCBmgiIiIiIgkYoImIiIiIJGCAJiIiIiKSgAGaiIiIiEgCBmgiIiIiIgkYoImIiIiIJGCA\\nJiIiIiKSgAGaiIiIiEgCBmgiIiIiIgkYoImIiIiIJGCAJiIiIiKSgAGaiIiIiEgCBmgiIiIiIgkY\\noImIiIiIJGCAJiIiIiKSgAGaiIiIiEgCBmgiIiIiIgkYoKnTc3FyhLOTg8nHy1yd4eLk2OL9RERE\\nnc1L0bPx3394Gg72dh3dFAJg3dENoI7l7uaC0vIKODs6wMrKCqXlFWhqUmod80zUNMx7dALmLv9f\\nYduuzX\\/B9z8fxhc797dZ2\\/oF++KFp59AcEBvKJXAtax8fPrVD8jKvSV6\\/LiRQ\\/BM1CPo1dMDAJB3\\nswifff0jLl7OMmk\\/ERFRZ2FvZwtraytUVFbD3c0FkRFy2NvZwsc7EZnZN8x2nvCwAZg1bRz6B\\/vB\\n3s7WbM9rTE1tHa5ez8Oe\\/cdxNvWKyY9zdLCDlaUVyiur2rB1xjFAd2N9vD3h4uwIRVkFfH284Ozk\\ngOSL11DX1NDRTQMAxCydB6+e7vj+58OwsrLE44+MwytL5uCNdz\\...
[ai] Turning screenshot into HTML image for use with canvas
[ai] Getting screenshot slices for each element
[ai] Making label predictions based on element images
tf.loadFrozenModel() is going away. Use tf.loadGraphModel() instead, and note the positional argument changes. You can disable deprecation warnings with tf.disableDeprecationWarnings().

============================
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================

tf.fromPixels() is renamed to tf.browser.fromPixels(), please switch to the new method as the old method will be removed in TensorFlow.js 1.0. You can disable deprecation warnings with tf.disableDeprecationWarnings().

[ai] Predictions for 29 element(s) took 345.222 seconds
[ai] Found 0 matching elements
[ai] Resetting element response attribute setting to original value: ""
[UiAutomator2] Forwarding the following settings to the UiAutomator2 server: ["elementResponseAttributes"]
[debug] [WD Proxy] Matched '/appium/settings' to command name 'updateSettings'

**Comment by jlipps** [comment]
@BSudheerR i don't see any issues here in the log, other than the warning from tensorflow, which isn't fatal. but it does suggest maybe something wasn't installed correctly, since `@tensorflow/tjfs-node` is indeed a dependency of this project, and is required [here](https://github.com/testdotai/appium-classifier-plugin/blob/master/lib/classifier.js#L11)

**Comment by BSudheerR** [comment]
Thanks @jlipps . npm i @tensorflow/tfjs-node solves my problems. Also This one "[ai] Found 0 matching elements" is because the cart element which i am trying is unable to find my plug in , even after changing the matching confidence to 0.1 , Not sure if it is issue with model or cart Image matching .. HOwever I could able to match with other elements and perform Action.

**Comment by jlipps** [comment]
OK, good to know. Thanks!
