### ISSUE TITLE
Unable to run plugin

### ISSUE THREAD

**Issue by 12masta** [testdotai/appium-classifier-plugin#29]
I am using macOS Catalina and I am unable to run plugin with following output:

2020-01-09 00:30:14.874293: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-09 00:30:14.895300: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x102a3c6a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-09 00:30:14.895345: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

Any thoughts how to fixit?

**Comment by jlipps** [comment]
These are not errors as far as I can tell. Is there another problem you encountered?

**Comment by 12masta** [comment]
Thanks for response. Yeah, so basically I am running plugin, receiving those command and that's all. I don't have any other output and job is terminating. Screenshot attached does it mean that service is running?

<img width="682" alt="Screenshot 2020-01-09 at 08 51 35" src="https://user-images.githubusercontent.com/12436120/72048596-7157ab00-32bd-11ea-8310-561bff025dfd.png">

**Comment by jlipps** [comment]
This seems like a potential bug. Will look into it. Thanks!

**Comment by jlipps** [comment]
ok, version 4.0.2 has been published with the fix.

**Comment by Sh1nt0** [comment]
> Thanks for response. Yeah, so basically I am running plugin, receiving those command and that's all. I don't have any other output and job is terminating. Screenshot attached does it mean that service is running?
> 
> <img alt="Screenshot 2020-01-09 at 08 51 35" width="682" src="https://user-images.githubusercontent.com/12436120/72048596-7157ab00-32bd-11ea-8310-561bff025dfd.png">
> 
> I am trying to run it through _node test-ai-classifier_ because after installation even with -g parameter I am receiving following error in terminal:
> 
> -bash: test-ai-classifier: command not found
> 
> **EDIT**:
> Asking question was self-healthing expierience. :) I am realised that it is probably something more wrong with npm. Which was correct assumption. Currently I am struggling following issue:
> 
> Error: ENOENT: no such file or directory, open '/Users/marcinstanek/.nvm/versions/node/v12.14.1/lib/node_modules/test-ai-classifier/classifier-proto/classifier.proto'
> at Object.openSync (fs.js:440:3)
> at Object.readFileSync (fs.js:342:35)
> at fetch (/Users/marcinstanek/.nvm/versions/node/v12.14.1/lib/node_modules/test-ai-classifier/node_modules/protobufjs/src/root.js:160:34)
> at Root.load (/Users/marcinstanek/.nvm/versions/node/v12.14.1/lib/node_modules/test-ai-classifier/node_modules/protobufjs/src/root.js:194:13)
> at Root.loadSync (/Users/marcinstanek/.nvm/versions/node/v12.14.1/lib/node_modules/test-ai-classifier/node_modules/protobufjs/src/root.js:235:17)
> at Object.loadSync (/Users/marcinstanek/.nvm/versions/node/v12.14.1/lib/node_modules/test-ai-classifier/node_modules/@grpc/proto-loader/build/src/index.js:221:27)
> at main (/Users/marcinstanek/.nvm/versions/node/v12.14.1/lib/node_modules/test-ai-classifier/lib/rpc.js:28:34)
> at Object. (/Users/marcinstanek/.nvm/versions/node/v12.14.1/lib/node_modules/test-ai-classifier/lib/rpc.js:93:3)
> at Module._compile (internal/modules/cjs/loader.js:955:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
> at Module.load (internal/modules/cjs/loader.js:811:32)
> at Function.Module._load (internal/modules/cjs/loader.js:723:14)
> at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
> at internal/main/run_main_module.js:17:11
> 
> I am checked manually and there is no file at: /Users/marcinstanek/.nvm/versions/node/v12.14.1/lib/node_modules/test-ai-classifier/classifier-proto/classifier.proto
> 
> @jlipps I am took file from here: https://github.com/testdotai/classifier-proto/blob/990d9861f0368d06375b623bddb6b9c457bea807/classifier.proto and created manually, so finally I am successfully run the server:
> node-pre-gyp info ai-rpc Classification RPC server started on 0.0.0.0:50051
> 
> So much fun, but do you have some thoughts why was not there?

I am facing the same problem that the program terminates without any output. So can u share the way you solved it ? Thanks a lot!
![image](https://user-images.githubusercontent.com/35826922/89534364-5c2d0580-d827-11ea-88de-2f06ab3e2955.png)
