### ISSUE TITLE
ERROR： test-ai-classifier@4.0.2 install error->node-gyp rebuild,No such file or directory

### ISSUE THREAD

**Issue by sjywzz** [testdotai/appium-classifier-plugin#36]
- Version info：

npm@6.4.1
node@v10.15.0
Appium@1.16.0
CentOS Linux release 7.4.1708

- Install directory：
cd /root/download/node-v10.15.0-linux-x64/lib/node_modules/appium

- Error info：

>node-pre-gyp WARN Using request for node-pre-gyp https download 
>[grpc] Success: "/root/download/node-v10.15.0-linux-x64/lib/node_modules/_appium@1.16.0@appium/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" is installed via remote
	
> test-ai-classifier@4.0.2 install /root/download/node-v10.15.0-linux-x64/lib/node_modules/_appium@1.16.0@appium/node_modules/test-ai-classifier
> node-gyp rebuild
	
>make: Entering directory `/root/download/node-v10.15.0-linux-x64/lib/node_modules/_appium@1.16.0@appium/node_modules/test-ai-classifier/build'
	  CXX(target) Release/obj.target/test-ai-classifier/cc/main.o

>In file included from ../cc/main.cc:3:0:
>../cc/detection.h:6:83: fatal error: ../node_modules/@tensorflow/tfjs-node/deps/include/tensorflow/c/c_api.h: No such file or directory
	 #include "../node_modules/@tensorflow/tfjs-node/deps/include/tensorflow/c/c_api.h"
	                                                                                   ^
compilation terminated.

- Question: is this caused by the wrong path in this file""test-ai-classifier/cc/main.cc""?

    -[error file]:/root/download/node-v10.15.0-linux-x64/lib/node_modules/_appium@1.16.0@appium/node_modules/test-ai-classifier/cc/main.cc
    -[ error line]:#include "../node_modules/@tensorflow/tfjs-node/deps/include/tensorflow/c/c_api.h"
    -[tensorflow directory]：
/root/download/node-v10.15.0-linux-x64/lib/node_modules/_appium@1.16.0@appium/node_modules/@tensorflow/tfjs-node/deps/include/tensorflow

**Comment by dutradev** [comment]
hi @sjywzz , you should install tensorflow/tfjs-node in folder Appium before install plugin test-ai-classifier. Because during the installation process, the plugin run build.

https://www.npmjs.com/package/@tensorflow/tfjs-node

**Comment by sjywzz** [comment]
oh yes! thanks~~~~
