### ISSUE TITLE
The following capabilities were provided, but are not recognized by appium: customFindModules

### ISSUE THREAD

**Issue by ericsavoiewaltz** [testdotai/appium-classifier-plugin#6]
[Appium] Welcome to Appium v1.9.2-beta.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

Running Appium v1.9.2-beta.2 and I get "not recognized by appium: customFindModules" 
"      caps:       {
          platformName: fake
          browserName: info,
          versionNumber: goes,
          deviceName: here,
          wdaLocalPort: 8001,
          udid: 'auto',
          app: nda,
          automationName: over,
          noReset: compliance,
          xcodeOrgId: thanks,
          xcodeSigningId: for,
          useNewWDA: understanding,
          newCommandTimeout: 10000,
          customFindModules: {
              "ai": "test-ai-classifier"
          },
          shouldUseCompactResponses: false"

Can anyone tell me why my Appium server won't recognize the new capability?

**Comment by jlipps** [comment]
Hi,

This would be an Appium error and not an error with this plugin code. I'm going to close here, but please open an issue at appium/appium and @-mention me.

And as a preview, we'll need the full Appium logs (redacted if you like) to help out there.
